---
- name: Install custom hosts file on Linux.
  become: true
  ansible.builtin.template:
    src: hostsfile.j2
    dest: "{{ hostsfile_hosts_path }}"
    owner: root
    group: root
    mode: '0644'
    backup: "{{ hostsfile_backup | default('true') }}"
  when: ansible_system | lower == "linux"

- name: Install custom hosts file on Windows.
  become: true
  ansible.windows.win_template:
    src: hostsfile.j2
    dest: "{{ hostsfile_hosts_path }}"
    backup: "{{ hostsfile_backup | default('true') }}"
  when: ansible_os_family | lower == "windows"
